name: Node.js CI

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v2
    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with: 
        registry: ghcr.io
        username: ${{ github.actor}}
        password: ${{ secrets.GITHUB_TOKEN}}

    - name: build docker image
      run: |
        docker build . --tag ghcr.io/finalproject-26-42-45/backend
        docker images
    - name: push docker iamges to registry
      run: |
        docker push ghcr.io/finalproject-26-42-45/backend
        
