name: Node.js CI

on:
  push:
    branches: 
    - 'master'

jobs:
  build:
    run-on: ubantu-latest
    steps:
    - uses: action/checkout@v2
    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with: 
        registry: ghcr.io
        username: ${{ github.actor}}
        password: ${{ secrets.GITHUB_TOKEN}}
    - name: create .env
      run: |
        touch .env
        echo DATABASE_URL=${{ secrets.DATABASE }} >> .env
        echo ACCESS_TOKEN_SECRET=${{ secret.ACCESS_TOKEN_SECRET }} >> .env
        ls -a
        mkdir tmp

    - name: build docker image
      run: |
        docker build . --tag ghcr.io/finalproject-26-42-45/backend
        docker images
    - name: push docker iamges to registry
      run: |
        docker push ghcr.io/finalproject-26-42-45/backend
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh command using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            export CR_PAT=${{ secrets.GITHUB_TOKEN }} 
            echo $CR_PAT | sudo docker login ghcr.io -u jeongchedah --password-stdin
            sudo docker pull ghcr.io/finalproject-26-42-45/backend
            sudo docker images
            sudo docker rm backend -f
            sudo docker run -d --name backend --network foodrandnetwork --ip 172.18.0.3 ghcr.io/finalproject-26-42-45/backend